language: generic

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX="g++-6" CC="gcc-6"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: *sources
    - os: linux
      env: CXX="g++-8" CC="gcc-8"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-8
            - g++-8
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources: *sources
    - os: linux
      env: CXX="clang++-5.0" CC="clang-5.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-5
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX="clang++-4.0" CC="clang-4.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5
            - cmake
            - cmake-data
            - binutils-dev
            - zlib1g-dev
            - libc6-dev
            - libboost-system-dev
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - linux-libc-dev
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/otf2-2.1

install:
  - OTF2_VERSION=2.1 # Update cache too when changing this!
  - OTF2_DIR=${TRAVIS_BUILD_DIR}/deps/otf2-${OTF2_VERSION}
  - |
    if [ -z "$(ls -A ${OTF2_DIR})" ]; then
      wget http://www.vi-hps.org/upload/packages/otf2/otf2-${OTF2_VERSION}.tar.gz
      tar -xf otf2-${OTF2_VERSION}.tar.gz
      (cd otf2-${OTF2_VERSION} && ./configure --prefix=${OTF2_DIR} && make -j2 install)
    fi
  - export CMAKE_PREFIX_PATH=${OTF2_DIR}:${CMAKE_PREFIX_PATH}

before_script:
  - sudo apt-get --no-install-suggests --no-install-recommends --force-yes install libiberty-dev

script:
  - cmake --version
  - cmake . -DUSE_RADARE=OFF -DUSE_PERF_CLOCKID=OFF
  - make
  - ctest -V .
